name: "Release"
on: [ workflow_dispatch ]
jobs:
  build-and-release:
    name: Build and Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: If testing with Act, dummy in "gh"
        if: ${{ env.ACT }}
        run: echo -e "echo Right now I would be running \"gh \$@\"" > /usr/local/bin/gh ; chmod +x /usr/local/bin/gh
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get version from tag name
        run: |
          EXACT_VERSION_TAG=$(git describe --tags --exact-match 2>/dev/null) ;
          LAST_VERSION_TAG=$(git describe --tags 2>/dev/null | echo "UNKNOWN") ;
          HASH=$(git rev-parse --short HEAD) ;
          TAG_NAME=${EXACT_VERSION_TAG:-$LAST_VERSION_TAG-$HASH} ;
          echo "Apparently we're building $TAG_NAME" ;
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV ;
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Build
        run: python -m pip install --upgrade pip setuptools wheel build ; python -m build -w
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --generate-notes --draft --repo="$GITHUB_REPOSITORY" --title="$TAG_NAME" "$TAG_NAME" ;
          gh release upload --clobber "$TAG_NAME" dist/*.whl
